### ISSUE TITLE
[HCA Portal] Migrate Portal to Nextjs/findable-ui

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-portal#2104]
### Tasks
- [x] [[HCA Portal] Create Next.js instance in Portal](https://github.com/DataBiosphere/data-portal/issues/2112)
- [x] [[HCA Portal] Configure dev environment for Next.js Portal](https://github.com/clevercanary/findable-tf/issues/18)
- [x] [[HCA Portal] Configure prod environment for Next.js Portal](https://github.com/clevercanary/findable-tf/issues/19)

**Comment by NoopDog** [comment]
Complete
